CREATE TABLE IF NOT EXISTS company_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  trade_name VARCHAR(180),
  legal_name VARCHAR(180),
  cnpj VARCHAR(18),
  state_registration VARCHAR(40),
  municipal_registration VARCHAR(40),
  cnae VARCHAR(20),
  tax_regime VARCHAR(80),
  phone VARCHAR(30),
  whatsapp VARCHAR(30),
  email VARCHAR(160),
  zip_code VARCHAR(12),
  street VARCHAR(180),
  number VARCHAR(20),
  complement VARCHAR(120),
  district VARCHAR(120),
  city VARCHAR(120),
  state CHAR(2),
  country VARCHAR(80),
  logo_url TEXT,
  logo_filename VARCHAR(255),
  primary_color VARCHAR(20),
  default_theme VARCHAR(40),
  admin_name VARCHAR(160),
  admin_email VARCHAR(160),
  admin_phone VARCHAR(30),
  admin_user_id UUID REFERENCES usuarios(id),
  admin_access_profile VARCHAR(40),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
